### ISSUE TITLE
ERROR make failed

### ISSUE THREAD

**Issue by dasito26** [m6w6/ext-propro#7]
I try to install propro, but several times I get this error.

About my system:
<pre><code>Ubuntu 20.04 LTS

PEAR Version: 1.10.13
PHP Version: 8.0.19
Zend Engine Version: 4.0.19

PHP 8.0.19 (cli) (built: May 17 2022 18:48:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies

libcurl4 is already the newest version (7.68.0-1ubuntu2.11)
libtool is already the newest version (2.4.6-14)
libcurl4-gnutls-dev is already the newest version (7.68.0-1ubuntu2.11)
libgnutls28-dev is already the newest version (3.6.13-2ubuntu1.6).
</pre></code>

pecl install propro
<pre><code>root@mx21:~# pecl install propro
downloading propro-2.1.0.tgz ...
Starting to download propro-2.1.0.tgz (14,253 bytes)
.....done: 14,253 bytes
8 source files, building
running: phpize
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
building in /tmp/pear/temp/pear-build-rootJV7Ws5/propro-2.1.0
running: /tmp/pear/temp/propro/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking for system library directory... lib
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib
checking for PHP extension directory... /usr/lib/php/20200930
checking for PHP installed headers prefix... /usr/include/php/20200930
checking if debug is enabled... no
checking if zts is enabled... no
checking for gawk... gawk
checking whether to enable property proxy support... yes, shared
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... (cached) gawk
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC -DPIC
checking if cc PIC flag -fPIC -DPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking if cc supports -c -o file.o... (cached) yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: patching config.h.in
configure: creating ./config.status
config.status: creating config.h
config.status: executing libtool commands
running: make
/bin/bash /tmp/pear/temp/pear-build-rootJV7Ws5/propro-2.1.0/libtool --mode=compile cc -I. -I/tmp/pear/temp/propro -I/tmp/pear/temp/pear-build-rootJV7Ws5/propro-2.1.0/include -I/tmp/pear/temp/pear-build-rootJV7Ws5/propro-2.1.0/main -I/tmp/pear/temp/propro -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib -I/tmp/pear/temp/propro/src  -DHAVE_CONFIG_H  -g -O2    -c /tmp/pear/temp/propro/src/php_propro_api.c -o src/php_propro_api.lo
libtool: compile:  cc -I. -I/tmp/pear/temp/propro -I/tmp/pear/temp/pear-build-rootJV7Ws5/propro-2.1.0/include -I/tmp/pear/temp/pear-build-rootJV7Ws5/propro-2.1.0/main -I/tmp/pear/temp/propro -I/usr/include/php/20200930 -I/usr/include/php/20200930/main -I/usr/include/php/20200930/TSRM -I/usr/include/php/20200930/Zend -I/usr/include/php/20200930/ext -I/usr/include/php/20200930/ext/date/lib -I/tmp/pear/temp/propro/src -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/propro/src/php_propro_api.c  -fPIC -DPIC -o src/.libs/php_propro_api.o
/tmp/pear/temp/propro/src/php_propro_api.c: In function ‘get_container_value’:
/tmp/pear/temp/propro/src/php_propro_api.c:368:58: warning: passing argument 2 of ‘zend_read_property’ from incompatible pointer type [-Wincompatible-pointer-types]
  368 |   found_value = zend_read_property(Z_OBJCE_P(container), container,
      |                                                          ^~~~~~~~~
      |                                                          |
      |                                                          zval * {aka struct _zval_struct *}
In file included from /usr/include/php/20200930/main/php.h:36,
                 from /tmp/pear/temp/propro/src/php_propro_api.c:18:
/usr/include/php/20200930/Zend/zend_API.h:407:16: note: expected ‘zend_object *’ {aka ‘struct _zend_object *’} but argument is of type ‘zval *’ {aka ‘struct _zval_struct *’}
  407 | ZEND_API zval *zend_read_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zend_bool silent, zval *rv);
      |                ^~~~~~~~~~~~~~~~~~
/tmp/pear/temp/propro/src/php_propro_api.c: In function ‘set_container_value’:
/tmp/pear/temp/propro/src/php_propro_api.c:421:46: warning: passing argument 2 of ‘zend_update_property’ from incompatible pointer type [-Wincompatible-pointer-types]
  421 |   zend_update_property(Z_OBJCE_P(container), container,
      |                                              ^~~~~~~~~
      |                                              |
      |                                              zval * {aka struct _zval_struct *}
In file included from /usr/include/php/20200930/main/php.h:36,
                 from /tmp/pear/temp/propro/src/php_propro_api.c:18:
/usr/include/php/20200930/Zend/zend_API.h:387:74: note: expected ‘zend_object *’ {aka ‘struct _zend_object *’} but argument is of type ‘zval *’ {aka ‘struct _zval_struct *’}
  387 | ZEND_API void zend_update_property(zend_class_entry *scope, zend_object *object, const char *name, size_t name_length, zval *value);
      |                                                             ~~~~~~~~~~~~~^~~~~~
/tmp/pear/temp/propro/src/php_propro_api.c: In function ‘zm_startup_propro’:
/tmp/pear/temp/propro/src/php_propro_api.c:680:44: warning: assignment to ‘zend_object_get_gc_t’ {aka ‘struct _zend_array * (*)(struct _zend_object *, struct _zval_struct **, int *)’} from incompatible pointer type ‘HashTable * (*)(zval *, zval **, int *)’ {aka ‘struct _zend_array * (*)(struct _zval_struct *, struct _zval_struct **, int *)’} [-Wincompatible-pointer-types]
  680 |  php_property_proxy_object_handlers.get_gc = get_gc;
      |                                            ^
/tmp/pear/temp/propro/src/php_propro_api.c:681:52: warning: assignment to ‘zend_object_get_debug_info_t’ {aka ‘struct _zend_array * (*)(struct _zend_object *, int *)’} from incompatible pointer type ‘HashTable * (*)(zval *, int *)’ {aka ‘struct _zend_array * (*)(struct _zval_struct *, int *)’} [-Wincompatible-pointer-types]
  681 |  php_property_proxy_object_handlers.get_debug_info = get_debug_info;
      |                                                    ^
/tmp/pear/temp/propro/src/php_propro_api.c:682:36: error: ‘zend_object_handlers’ {aka ‘struct _zend_object_handlers’} has no member named ‘set’
  682 |  php_property_proxy_object_handlers.set = set_obj;
      |                                    ^
/tmp/pear/temp/propro/src/php_propro_api.c:683:36: error: ‘zend_object_handlers’ {aka ‘struct _zend_object_handlers’} has no member named ‘get’
  683 |  php_property_proxy_object_handlers.get = get_obj;
      |                                    ^
/tmp/pear/temp/propro/src/php_propro_api.c:684:49: warning: assignment to ‘zend_object_cast_t’ {aka ‘int (*)(struct _zend_object *, struct _zval_struct *, int)’} from incompatible pointer type ‘ZEND_RESULT_CODE (*)(zval *, zval *, int)’ {aka ‘enum <anonymous> (*)(struct _zval_struct *, struct _zval_struct *, int)’} [-Wincompatible-pointer-types]
  684 |  php_property_proxy_object_handlers.cast_object = cast_obj;
      |                                                 ^
/tmp/pear/temp/propro/src/php_propro_api.c:685:52: warning: assignment to ‘zend_object_read_dimension_t’ {aka ‘struct _zval_struct * (*)(struct _zend_object *, struct _zval_struct *, int,  struct _zval_struct *)’} from incompatible pointer type ‘zval * (*)(zval *, zval *, int,  zval *)’ {aka ‘struct _zval_struct * (*)(struct _zval_struct *, struct _zval_struct *, int,  struct _zval_struct *)’} [-Wincompatible-pointer-types]
  685 |  php_property_proxy_object_handlers.read_dimension = read_dimension;
      |                                                    ^
/tmp/pear/temp/propro/src/php_propro_api.c:686:53: warning: assignment to ‘zend_object_write_dimension_t’ {aka ‘void (*)(struct _zend_object *, struct _zval_struct *, struct _zval_struct *)’} from incompatible pointer type ‘void (*)(zval *, zval *, zval *)’ {aka ‘void (*)(struct _zval_struct *, struct _zval_struct *, struct _zval_struct *)’} [-Wincompatible-pointer-types]
  686 |  php_property_proxy_object_handlers.write_dimension = write_dimension;
      |                                                     ^
/tmp/pear/temp/propro/src/php_propro_api.c:687:51: warning: assignment to ‘zend_object_has_dimension_t’ {aka ‘int (*)(struct _zend_object *, struct _zval_struct *, int)’} from incompatible pointer type ‘int (*)(zval *, zval *, int)’ {aka ‘int (*)(struct _zval_struct *, struct _zval_struct *, int)’} [-Wincompatible-pointer-types]
  687 |  php_property_proxy_object_handlers.has_dimension = has_dimension;
      |                                                   ^
/tmp/pear/temp/propro/src/php_propro_api.c:688:53: warning: assignment to ‘zend_object_unset_dimension_t’ {aka ‘void (*)(struct _zend_object *, struct _zval_struct *)’} from incompatible pointer type ‘void (*)(zval *, zval *)’ {aka ‘void (*)(struct _zval_struct *, struct _zval_struct *)’} [-Wincompatible-pointer-types]
  688 |  php_property_proxy_object_handlers.unset_dimension = unset_dimension;
      |                                                     ^
make: *** [Makefile:228: src/php_propro_api.lo] Error 1
ERROR: `make' failed</code></pre>

**Comment by Jan-E** [comment]
Propro was discontinued for PHP 8:
https://github.com/m6w6/ext-propro/pull/5#issuecomment-664460186
