### ISSUE TITLE
Ext. propro does not supported by php-8.0

### ISSUE THREAD

**Issue by matthD-debug** [m6w6/ext-propro#8]
Hello,

I got a problem when i'm trying to build the project with php 8.0. In below the screenshot:

![Selection_007](https://user-images.githubusercontent.com/84901105/216589479-fdd8618c-af17-4d54-aca1-c9c3240e65ce.png)

Can you help me please?

Let me know if you need anything else,

Best regards,

**Comment by Jan-E** [comment]
There will not be a propro extension for PHP 8+. See https://github.com/m6w6/ext-propro/pull/5
